---

sudo: required
language: c
compiler: gcc
install:
    - sudo apt-get update
    - sudo apt-get install build-essential

script:
    - make clean
    - make
    - sudo ./run.sh 64 3 wlp2s0,wlp2s0 0 http://mirror.its.dal.ca/archlinux/iso/2016.10.01/archlinux-bootstrap-2016.10.01-i686.tar.gz 15 30 40

...
