---

sudo: required
language: c
compiler: gcc
install:
    - sudo apt-get update
    - sudo apt-get install build-essential

script:
    - make clean
    - make
    - sudo make test-1M
    - sudo make test-5M

...
